### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by davipatricio** [davipatricio/denky-rewrite#1]
## Interactions
- [ ] Check permissions on `interactionCreate` event (@davipatricio)

## Commands
- [ ] Help command (@davipatricio)
- [ ] Text subcommands (@davipatricio)
  - [ ] Clapify
  - [ ] Emojify
  - [ ] Invert
  - [ ] Translate
  - [ ] Vaporwave
- [ ] Minigame subcommands (@davipatricio)
  - [ ] Akinator
  - [x] Quiz
  - [ ] 2048
  - [ ] TicTacToe
  - [ ] Snake

## Utils
- [ ] Redis wrapper (@BONEE4)
